name: Release

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
      next_version: ${{ steps.increment_version.outputs.next_version }}
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        architecture: 'x64'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install nuitka
        Invoke-RestMethod -Uri "https://drive.usercontent.google.com/download?id=1-SaAuxdnOU5oIPTXrHOg6cfgyI8-3lq6&export=download" -OutFile ".\_internal\opencv_world490.dll"
      
    - name: Build
      run: |
        cd modules
        python -m nuitka --windows-uac-admin --standalone  --follow-imports --output-filename=update --assume-yes-for-downloads download.py
        cd..
        Copy-Item -Path "$pwd\modules\download.dist\*" -Destination "$pwd\_internal\update\" -Recurse -Force -Confirm:$false
        python -m nuitka --windows-disable-console --windows-uac-admin --standalone --include-data-dir=_internal/=_internal --include-data-files=_internal/*.dll=_internal/ --include-data-files=_internal/*.exe=_internal/ --include-data-files=_internal/update/*.dll=_internal/update/ --include-data-files=_internal/update/*.pyd=_internal/update/ --follow-imports --output-filename=UmaKey --enable-plugin=tk-inter main.py
        Copy-Item -Path "$pwd\Launcher.exe" -Destination "$pwd\main.dist\" -Force -Confirm:$false
        Compress-Archive -Path ".\main.dist\*" -DestinationPath "UmaKey.zip"
        
    - name: Extract version number
      id: extract_version
      run: |
        $version = (Invoke-RestMethod -Uri "https://api.github.com/repos/${{ github.repository }}/releases/latest" | Select-Object -ExpandProperty tag_name)
        Write-Output 'Latest tag: $version'
        Write-Output "version=$version" >> $env:GITHUB_OUTPUT

    - name: Increment version number
      id: increment_version
      run: |
        $version = "${{ steps.extract_version.outputs.version }}"
        $major, $minor, $patch = $version.Replace('v', '').Split(".")
        $next_patch = [int]$patch + 1
        $next_version = "v$major.$minor.$next_patch"
        echo "Next tag: $next_version"
        Write-Output "next_version=$next_version" >> $env:GITHUB_OUTPUT
        
    - name: Upload Release Asset
      id: update-release-asset
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: ${{ steps.increment_version.outputs.next_version }}
        files: |
          ./UmaKey.zip
        prerelease: true
