name: Release

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Build
      run: |
        cargo build --release
        Copy-Item ".\target\release\umakey.exe" ".\UmaKey.exe" -Force
        Compress-Archive -Path ".\UmaKey.exe", ".\config.json" -DestinationPath "UmaKey.zip" -Force

    - name: Read version from Cargo.toml
      id: version
      run: |
        $ver = (Select-String -Path Cargo.toml -Pattern '^version = "(.+)"' | Select-Object -First 1).Matches[0].Groups[1].Value
        echo "Tag: v$ver"
        Write-Output "tag=v$ver" >> $env:GITHUB_OUTPUT

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: ${{ steps.version.outputs.tag }}
        files: |
          ./UmaKey.zip
        prerelease: true
